version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/nlp-codedeploy
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/reload-pm2.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: Scripts/BUILD.sh
      timeout: 300
      runas: ubuntu