version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
#  secrets-manager:
#      NTC_TOKEN: nlp/app/github
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
       docker: 18
      # name: version
    commands:
       - sudo yum install git
       - sudo yum install -y yum-utils
       - sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
       - sudo yum install docker-ce docker-ce-cli containerd.io
       - sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
       - sudo chmod +x /usr/local/bin/docker-compose
#  pre_build:
#    commands:
#       - command
      # - command
  build:
    commands:
      - sudo docker network create nlp_project_default
      - sudo docker-compose build --build-arg NTC_TOKEN="$(echo $NTC_TOKEN)"
  post_build:
    commands:
      - sudo docker-compose up
      # - command
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths