version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
#  secrets-manager:
#      NTC_TOKEN: nlp/app/github
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
       docker: latest
      # name: version
    commands:
       - echo sudo yum install git
       - echo sudo yum install -y yum-utils
       - echo sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
       - echo sudo yum install docker-ce docker-ce-cli containerd.io
       - echo sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
       - echo sudo chmod +x /usr/local/bin/docker-compose
#  pre_build:
#    commands:
#       - command
      # - command
  build:
    commands:
      - echo sudo docker network create nlp_project_default
      - echo sudo docker-compose build --build-arg NTC_TOKEN="$(echo $NTC_TOKEN)"
      - echo sudo yum install jq -y
      - ContainerName="todo"
      - ImageURI=$(cat imageDetail.json | jq -r '.ImageURI')
      - printf '[{"name":"CONTAINER_NAME","imageUri":"IMAGE_URI"}]' > imagedefinitions.json
      - sed -i -e "s|CONTAINER_NAME|$ContainerName|g" imagedefinitions.json
      - sed -i -e "s|IMAGE_URI|$ImageURI|g" imagedefinitions.json
      - cat imagedefinitions.json
  post_build:
    commands:
      - echo sudo docker-compose up -d
      # - command
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
artifacts:
  files:
    - imagedefinitions.json
#cache:
  #paths:
    # - paths