version: '3.9'

services:
  web:
    restart: always
    container_name: nlp_project
    build: 
      context: ./
      dockerfile: ./services/web/Dockerfile
      args:
        ssh_prv_key: $$(cat ~/.ssh/id_rsa)
        ssh_pub_key: $$(cat ~/.ssh/id_rsa.pub)
    command: gunicorn -b 0.0.0.0:5000 wsgi:app --timeout 120
    networks:
      - nlp_project
    volumes:
      - /static/nlp_project:/usr/nginx/html/products
    environment:
      - NODE_ENV=prod
      - MONGO_DB_USERNAME=root
      - MONGO_DB_PASSWORD=password
    expose:
      - 5000

  #Specify the network these containers will run on
  nginx:
    container_name: nginx
    build: 
      context: ../.
      dockerfile: ./NLP_Project/services/nginx/Dockerfile
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
      - regex
      - swell 
    networks:
      - nlp_project
    command: "/bin/sh -c 'while :; do sleep 12h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - /static/regex:/usr/nginx/html/regex
      - /static/swell:/usr/nginx/html/swell
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
  
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - nlp_project
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  regex:
    restart: always
    container_name: regex
    build: 
      context: ../regex/
      dockerfile: ../regex/services/web/Dockerfile
    command: gunicorn -b 0.0.0.0:8080 wsgi:app --timeout 120
    volumes:
      - /static/regex:/usr/nginx/regex/html
    environment:
      - NODE_ENV=prod    
    networks:
      - nlp_project
    expose:
      - 8080
  
  swell:
    restart: always
    container_name: swell
    build: 
      context: ../swell-watchers-app/
      dockerfile: ../swell-watchers-app/services/swell-watchers-app/Dockerfile
    command: gunicorn -b 0.0.0.0:5001 wsgi:app --timeout 120
    volumes:
      - /static/swell:/usr/nginx/swell/html
    environment:
      - NODE_ENV=prod
      - API_TOKEN=pk.eyJ1IjoiY3dpcmtzMDEiLCJhIjoiY2t1MngzbTRoNDVqaTJ2cGlicWc2a3g2aCJ9.un0FXVnmyP2au1a0X7nGyA
      - MAPBOX_STYLE=mapbox://styles/cwirks01/ckun70qvf0bdv18kq1hai6k3q
    networks:
      - nlp_project
    expose:
      - 5001

networks:
  nlp_project:
    external: true