version: '3.9'

services:
  web:
    restart: always
    build: 
      context: ./
      dockerfile: ./services/web/Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 main:main
    networks:
      - nlp_project
    expose:
      - 5000
    volumes:
      - /usr/nginx/html
    environment:
      - NODE_ENV=prod

  #Specify the network these containers will run on
  nginx:
    build: ./services/nginx
    restart: always
    ports:
      - 1337:80
    depends_on:
      - web

networks:
  nlp_project:
    external:
      name: nlp_project_default