version: '3.9'

services:
  web:
    restart: always
    build: .
    networks:
      - nlp_project
    ports:
      - "8000:8000"
      - "443:443"
    volumes:
      - /usr/share/nginx/html
    environment:
      - NODE_ENV=prod
      - PORT=8000

    #Specify the network these containers will run on
  nginx:
    image: nginx
    depends_on:
    - web
    expose:
      - "80"

networks:
  nlp_project:
    external:
      name: nlp_project_default