version: '3.9'

services:
  web:
    restart: always
    build: 
      context: ./
      dockerfile: ./services/web/Dockerfile
    command: gunicorn nlp_project.wsgi.app --bind 0.0.0.0:5000 wsgi:app
    networks:
      - nlp_project
    ports: 
      - 5000:5000
    volumes:
      - /usr/nginx/html
    environment:
      - NODE_ENV=prod

  #Specify the network these containers will run on
  nginx:
    build: ./services/nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - web

networks:
  nlp_project:
    external:
      name: nlp_project_default