version: '3.9'

services:
  web:
    restart: always
    build: 
      context: ./
      dockerfile: ./services/web/Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 app:app
    networks:
      - nlp_project
    ports: 
      - 5000:5000
    volumes:
      - /usr/nginx/html
    environment:
      - NODE_ENV=prod
      - GIT_TOKEN=$$GIT_TOKEN
    depends_on:
      - mongodb

  #Specify the network these containers will run on
  nginx:
    build: ./services/nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - web
      - mongodb

  mongodb:
    image : mongo
    container_name: mongodb
    command: mkdir -pv mongodb/database
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME_FILE=$$MONGO_DB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD_FILE=$$MONGO_DB_PASSWORD
    volumes:
      - /home/ec2-user/mongodb/database:/data/db
    ports:
      - 27019:27017
    restart: always

networks:
  nlp_project:
    external:
      name: nlp_project_default