version: '3.9'

services:
  web:
    restart: always
    container_name: nlp_project
    build: 
      context: ./
      dockerfile: ./services/web/Dockerfile
      args:
        ssh_prv_key: $$(cat ~/.ssh/id_rsa)
        ssh_pub_key: $$(cat ~/.ssh/id_rsa.pub)
    command: gunicorn -b 0.0.0.0:5000 wsgi:app --timeout 120
    networks:
      - nlp_project
    volumes:
      - /usr/nginx/html
    environment:
      - NODE_ENV=prod
      - MONGO_DB_USERNAME=$${env:MONGO_DB_USERNAME}
      - MONGO_DB_PASSWORD=$${env:MONGO_DB_PASSWORD}
    expose:
      - 5000

  #Specify the network these containers will run on
  nginx:
    container_name: nginx
    build: 
      context: ../.
      dockerfile: ./NLP_Project/services/nginx/Dockerfile
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
      - regex
      - swell 
    networks:
      - nlp_project
    volumes:
      - /static/regex:/usr/nginx/html/regex
      - /static/swell:/usr/nginx/html/swell
      - /certbot/www:/var/www/certbot:ro
      - /certbot/conf:/etc/nginx/ssl
  
  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --email cwirks01@gmail.com --agree-tos --no-eff-email -d testing-dev.dev -d www.testing-dev.dev
    volumes:
      - /certbot/www:/var/www/certbot:rw
      - /certbot/conf:/etc/letsencrypt:rw
    networks:
      - nlp_project

  regex:
    restart: always
    container_name: regex
    build: 
      context: ../regex/
      dockerfile: ../regex/services/web/Dockerfile
    command: gunicorn -b 0.0.0.0:8080 wsgi:app --timeout 120
    volumes:
      - /static/regex:/usr/nginx/regex/html
    environment:
      - NODE_ENV=prod    
    networks:
      - nlp_project
    expose:
      - 8080
  
  swell:
    restart: always
    container_name: swell
    build: 
      context: ../swell-watchers-app/
      dockerfile: ../swell-watchers-app/services/swell-watchers-app/Dockerfile
    command: gunicorn -b 0.0.0.0:5001 wsgi:app --timeout 120
    volumes:
      - /static/swell:/usr/nginx/swell/html
    environment:
      - NODE_ENV=prod
      - API_TOKEN=pk.eyJ1IjoiY3dpcmtzMDEiLCJhIjoiY2t1MngzbTRoNDVqaTJ2cGlicWc2a3g2aCJ9.un0FXVnmyP2au1a0X7nGyA
      - MAPBOX_STYLE=mapbox://styles/cwirks01/ckun70qvf0bdv18kq1hai6k3q
    networks:
      - nlp_project
    expose:
      - 5001

networks:
  nlp_project:
    external: true