version: '3.9'

services:
  web:
    restart: always
    container_name: nlp_project
    build: 
      context: ./
      dockerfile: ./services/web/Dockerfile
      args:
        ssh_prv_key: $$(cat ~/.ssh/id_rsa)
        ssh_pub_key: $$(cat ~/.ssh/id_rsa.pub)
        git_username: $${env:MONGO_DB_USERNAME}
        git_password: $${env:GITHUB_TOKEN}
    command: gunicorn -b 0.0.0.0:5000 wsgi:app --timeout 120
    networks:
      - nlp_project
    volumes:
      - /usr/nginx/html
    environment:
      - NODE_ENV=prod
      - MONGO_DB_USERNAME=$${env:MONGO_DB_USERNAME}
      - MONGO_DB_PASSWORD=$${env:MONGO_DB_PASSWORD}
    ports:
      - 5000:80

  #Specify the network these containers will run on
  nginx:
    container_name: nginx
    build: 
      context: ../.
      dockerfile: ./NLP_Project/services/nginx/Dockerfile
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
      - regex    
    networks:
      - nlp_project
    volumes:
      - /usr/nginx/html
  
  regex:
    restart: always
    container_name: regex
    build: 
      context: ../regex/
      dockerfile: ../regex/services/web/Dockerfile
    command: gunicorn -b 0.0.0.0:8080 wsgi:app --timeout 120
    volumes:
      - /usr/nginx/html
    environment:
      - NODE_ENV=prod    
    networks:
      - nlp_project
    ports:
      - 8080:80

networks:
  nlp_project:
    external:
      name: nlp_project_default