version: '3.9'

services:
  web:
    restart: always
    build: .
    networks:
      - nlp_project
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /usr/share/nginx/html

    #Specify the network these containers will run on
  nginx:
    image: nginx
    depends_on:
    - web
    expose:
      - "80"

networks:
  nlp_project:
    external:
      name: nlp_project_default