version: '3.9'

services:
  web:
    restart: always
    build: 
      context: ./
      dockerfile: ./services/web/Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    networks:
      - nlp_project
    ports: 
      - 5000:5000
    volumes:
      - /usr/nginx/html
    environment:
      - NODE_ENV=prod

  #Specify the network these containers will run on
  nginx:
    build: ./services/nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - web
      - mongodb

  mongodb:
    image : mongo
    container_name: mongodb
    build: ./services/mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/ec2-user/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: always
    depends_on:
      - web


networks:
  nlp_project:
    external:
      name: nlp_project_default